INSERT INTO ship (name, description) VALUES
('Millennium Falcon', 'Nave de carga modificada, famosa por su velocidad.'),
('Star Destroyer', 'Nave capital del Imperio, armada y con gran capacidad.'),
('TIE Fighter', 'Caza estelar del Imperio con diseño característico.'),
('X-Wing', 'Caza estelar de la Alianza Rebelde, famoso por su agilidad.'),
('Y-Wing', 'Bombardero utilizado por la Alianza Rebelde, conocido por su resistencia.'),
('A-Wing', 'Caza interceptor rápido y maniobrable de la Alianza Rebelde.'),
('B-Wing', 'Nave de asalto pesado utilizada por la Alianza Rebelde.'),
('Slave I', 'Nave de caza recompensas de Boba Fett.'),
('Nebulon-B Frigate', 'Fragata de escolta de la Alianza Rebelde.'),
('Executor', 'Super Destructor Estelar del Imperio, insignia de Darth Vader.'),
('Lambda Shuttle', 'Transporte utilitario del Imperio.'),
('E-Wing', 'Caza estelar desarrollado para la Nueva República.'),
('TIE Bomber', 'Nave del Imperio diseñada para ataques con bombas.'),
('MC80 Star Cruiser', 'Crucero estelar de la Alianza Rebelde.'),
('Z-95 Headhunter', 'Caza estelar anterior al X-Wing.'),
('U-Wing', 'Nave de transporte y asalto utilizada por la Rebelión.'),
('Vulture Droid', 'Caza estelar droide usado por la Confederación de Sistemas Independientes.'),
('Venator-class Star Destroyer', 'Destructor estelar utilizado durante las Guerras Clon.'),
('ARC-170', 'Caza estelar utilizado por la República durante las Guerras Clon.'),
('Wing', 'Nave de combate con diseño avanzado para agilidad y velocidad.');
